### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by kisyular** [kisyular/MI-449-SS17-740-js-collect-and-display-information-kPt9Fl#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://kisyular.github.io/MI-449-SS17-740-js-collect-and-display-information-kPt9Fl/) and meets the following criteria:

- [x] Use [this base HTML](https://gist.github.com/chrisvfritz/1b25d9037fb64e3486ea2df8179f9ce8) (feel free to change it) to build a simple app that generates the HTML for a dating profile [in this format](https://gist.github.com/chrisvfritz/4043b4d043610a2bb9cd26444c3e7a45), using information collected from the user
- [x] Show a preview of the dating profile with rendered HTML (e.g. `<em>hella charming</em>` should appear as _hella charming_)
- [x] Also show the raw, generated HTML inside the `<pre><code></code></pre>` elements (e.g. `<em>hella charming</em>` should appear as `<em>hella charming</em>`)
- [x] Both the preview and raw HTML should update live as the user enters their information
- [x] All JavaScript is in a separate `.js` file

**Comment by egillespie** [comment]
Hi @kisyular, the page looks pretty nice and I can see the page getting updated, but there's still some room for improvement.

### First and Last textboxes aren't using Bootstrap styles

It looks like you have a space in the `type` attribute for these two elements. It's causing them to look like browser-default textboxes instead of using Bootstrap styles.

### All JavaScript in a separate `.js` file

Your input elements are using `onkeyup="firstName()"` to call JavaScript. That counts as JavaScript! :wink:  Another (better) reason is that using the `onkeyup` attribute in HTML isn't as useful as calling `addEventListener` in JavaScript because you can only add one listener in HTML (JavaScript allows you to add many).

You mention in a JavaScript comment that you were getting an error when trying to use `addEventListener`. Do you know what the error was?

If you're still getting an error after you make these changes, please reach out to me on Slack and I'll help you troubleshoot!

### Profile is not consistently updating

It looks like you have different functions for each of the input boxes. This is causing only the last value changed to show up in the generated profile. We'd like you to update and show the _whole_ dating profile after every change.

This will require having only one function that is called by all of the different input boxes. This function will create the whole dating profile and update the two spots where it will get displayed.

Make sure you update `EMAIL_ADDRESS` and `PHONE_NUMBER` in the anchors, too!

---

Feel free to reach out to one of us if you have questions or get stuck. We're happy to help with issues before they get submitted for code review and much like in a professional setting, you don't have to figure this all out on your own. :smile: 

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! :rocket:

**Comment by kisyular** [comment]
@egillespie, I updated the function as you suggested, can you please take a look and let me know

**Comment by egillespie** [comment]
This is really coming along nicely!

There are just a few more things that are off:

### Email and Phone Number links

The text for the email and phone number are being updated, but the links are not. If you mouse-over or click on either one of them, you'll see that they always link to `mailto:EMAIL_ADDRESS` AND `tel:PHONE_NUMBER`. Can you update the links as well?

It may require you to recreate all of the HTML for the profile preview, which is okay.

### Generated HTML doesn't show HTML tags

The Generated HTML preview is only showing the values of the input/textareas and not all of the other HTML for the profile.

Also, if I type `<em>kinda handsome</em>` as my bio, it doesn't show "<em>kinda handsome</em>". When setting the content of the Generated HTML, you'll need to use `textContent` instead of `innerHTML`.

---

When you've pushed your changes to GitHub and your hosted site, comment back here and I’ll take another look.

Thanks! :rocket:

**Comment by kisyular** [comment]
@egillespie, I fixed the email and the phone issue.

I am wondering why the _**<em>kinda handsome</em>**_ does not work. It works pretty well on my preview
![screen shot 2017-02-07 at 17 40 32](https://cloud.githubusercontent.com/assets/15636554/22714946/d362c748-ed5c-11e6-9945-2a3111cddc63.png)

**Comment by kisyular** [comment]
@egillespie I am still struggling quite hard with how to include the _html_ tags in the **Generated HTML**.

**Comment by egillespie** [comment]
Updating the `preCode` element with `textContent` fixed the issue I was experiencing with `<em>kinda handsome</em>`. :+1: 

For the *Generated HTML*, you'll need to change your code a bit to make a string that contains all of the HTML that will go in both Preview and Generated HTML. It'll look something like this:

```js
var previewHtml = '<h4>Hi, my name is ' + firstName + ' ' + lastName + '</h4>' // .....
```

Then you'll update the Preview using `innerHTML` and the Generated HTML with `textContent`. That means your `firstName()`, `lastName()`, etc. functions won't set `innerHTML` themselves, they'll just call `updateProfile()` and it will do all the work.

Does that make sense? If not, message me on Slack or comment back here and I can elaborate a little more. :sunglasses:

**Comment by kisyular** [comment]
@egillespie, I update the code as you suggested. Kindly take a look

**Comment by egillespie** [comment]
This is fantastic! Good job on the follow-ups. :shipit:
